// settings/profile/notifications-alerts/index.tsx
'use client'

import type { JSX } from 'react'
import { useState } from 'react'
import { useTranslation } from 'react-i18next'

import { AdCheckbox, AdLabel, NucSettingsCard } from 'nucleify'

import './_index.scss'

type NotificationsState = {
  accountUpdates: boolean
  weeklyDigest: boolean
  pushEnabled: boolean
  mentions: boolean
  comments: boolean
  systemUpdates: boolean
}

export function NucUsersProfileNotificationsAlerts(): JSX.Element {
  const { t } = useTranslation()

  const [notifications, setNotifications] = useState<NotificationsState>({
    accountUpdates: true,
    weeklyDigest: false,
    pushEnabled: true,
    mentions: true,
    comments: true,
    systemUpdates: false,
  })

  return (
    <div>
      <NucSettingsCard heading={t('notifications-email-heading')}>
        <div className="profile-form">
          <div className="profile-form-toggle-row">
            <div>
              <AdLabel label={t('notifications-account-updates')} />
              <p className="profile-form-description">
                {t('notifications-account-updates-desc')}
              </p>
            </div>
            <AdCheckbox
              checked={notifications.accountUpdates}
              onChange={(event) =>
                setNotifications((prev) => ({
                  ...prev,
                  accountUpdates: Boolean(event.checked),
                }))
              }
            />
          </div>

          <div className="profile-form-toggle-row">
            <div>
              <AdLabel label={t('notifications-weekly-digest')} />
              <p className="profile-form-description">
                {t('notifications-weekly-digest-desc')}
              </p>
            </div>
            <AdCheckbox
              checked={notifications.weeklyDigest}
              onChange={(event) =>
                setNotifications((prev) => ({
                  ...prev,
                  weeklyDigest: Boolean(event.checked),
                }))
              }
            />
          </div>
        </div>
      </NucSettingsCard>

      <hr className="settings-card-divider" />

      <NucSettingsCard heading={t('notifications-push-heading')}>
        <div className="profile-form">
          <div className="profile-form-toggle-row">
            <div>
              <AdLabel label={t('notifications-push-enable')} />
              <p className="profile-form-description">
                {t('notifications-push-enable-desc')}
              </p>
            </div>
            <AdCheckbox
              checked={notifications.pushEnabled}
              onChange={(event) =>
                setNotifications((prev) => ({
                  ...prev,
                  pushEnabled: Boolean(event.checked),
                }))
              }
            />
          </div>
        </div>
      </NucSettingsCard>

      <hr className="settings-card-divider" />

      <NucSettingsCard heading={t('notifications-activity-heading')}>
        <div className="profile-form">
          <div className="profile-form-toggle-row">
            <div>
              <AdLabel label={t('notifications-mentions')} />
              <p className="profile-form-description">
                {t('notifications-mentions-desc')}
              </p>
            </div>
            <AdCheckbox
              checked={notifications.mentions}
              onChange={(event) =>
                setNotifications((prev) => ({
                  ...prev,
                  mentions: Boolean(event.checked),
                }))
              }
            />
          </div>

          <div className="profile-form-toggle-row">
            <div>
              <AdLabel label={t('notifications-comments')} />
              <p className="profile-form-description">
                {t('notifications-comments-desc')}
              </p>
            </div>
            <AdCheckbox
              checked={notifications.comments}
              onChange={(event) =>
                setNotifications((prev) => ({
                  ...prev,
                  comments: Boolean(event.checked),
                }))
              }
            />
          </div>

          <div className="profile-form-toggle-row">
            <div>
              <AdLabel label={t('notifications-updates')} />
              <p className="profile-form-description">
                {t('notifications-updates-desc')}
              </p>
            </div>
            <AdCheckbox
              checked={notifications.systemUpdates}
              onChange={(event) =>
                setNotifications((prev) => ({
                  ...prev,
                  systemUpdates: Boolean(event.checked),
                }))
              }
            />
          </div>
        </div>
      </NucSettingsCard>
    </div>
  )
}

// settings/profile/notifications-alerts/index.vue
<template>
  <nuc-settings-card :heading="t('notifications-email-heading')">
    <div class="profile-form">
      <div class="profile-form-toggle-row">
        <div>
          <ad-label :text="t('notifications-account-updates')" />
          <p class="profile-form-description">
            {{ t('notifications-account-updates-desc') }}
          </p>
        </div>
        <ad-checkbox v-model="notifications.accountUpdates" binary />
      </div>

      <div class="profile-form-toggle-row">
        <div>
          <ad-label :text="t('notifications-weekly-digest')" />
          <p class="profile-form-description">
            {{ t('notifications-weekly-digest-desc') }}
          </p>
        </div>
        <ad-checkbox v-model="notifications.weeklyDigest" binary />
      </div>
    </div>
  </nuc-settings-card>

  <hr class="settings-card-divider">

  <nuc-settings-card :heading="t('notifications-push-heading')">
    <div class="profile-form">
      <div class="profile-form-toggle-row">
        <div>
          <ad-label :text="t('notifications-push-enable')" />
          <p class="profile-form-description">
            {{ t('notifications-push-enable-desc') }}
          </p>
        </div>
        <ad-checkbox v-model="notifications.pushEnabled" binary />
      </div>
    </div>
  </nuc-settings-card>

  <hr class="settings-card-divider">

  <nuc-settings-card :heading="t('notifications-activity-heading')">
    <div class="profile-form">
      <div class="profile-form-toggle-row">
        <div>
          <ad-label :text="t('notifications-mentions')" />
          <p class="profile-form-description">
            {{ t('notifications-mentions-desc') }}
          </p>
        </div>
        <ad-checkbox v-model="notifications.mentions" binary />
      </div>

      <div class="profile-form-toggle-row">
        <div>
          <ad-label :text="t('notifications-comments')" />
          <p class="profile-form-description">
            {{ t('notifications-comments-desc') }}
          </p>
        </div>
        <ad-checkbox v-model="notifications.comments" binary />
      </div>

      <div class="profile-form-toggle-row">
        <div>
          <ad-label :text="t('notifications-updates')" />
          <p class="profile-form-description">
            {{ t('notifications-updates-desc') }}
          </p>
        </div>
        <ad-checkbox v-model="notifications.systemUpdates" binary />
      </div>
    </div>
  </nuc-settings-card>
</template>

<script setup lang="ts">
import { reactive } from 'vue'
import { useI18n } from 'vue-i18n'

const { t } = useI18n()

const notifications = reactive({
  accountUpdates: true,
  weeklyDigest: false,
  pushEnabled: true,
  mentions: true,
  comments: true,
  systemUpdates: false,
})
</script>

<style lang="scss">
@import 'index';
</style>
