// settings/profile/profile-actions/index.tsx
'use client'

import type { JSX } from 'react'
import { useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'

import { AdButton, AdDialog, flashToast } from 'nucleify'

import './_index.scss'

type ProfileEditDataType = {
  firstName: string
  lastName: string
  email: string
  phone_number: string
}

type ProfileEditFieldType = {
  name: string
  key: string
  label: string
  type: string
}

type NucProfileActionsProps = {
  userId: number
  currentLang: string
  accountSinceLabel: string
  editProfileData: ProfileEditDataType
  profileEditFields: ProfileEditFieldType[]
  onProfileSaved?: (value: ProfileEditDataType) => void
}

export function NucProfileActions({
  userId,
  currentLang,
  accountSinceLabel,
  editProfileData,
  profileEditFields,
  onProfileSaved,
}: NucProfileActionsProps): JSX.Element {
  const { t } = useTranslation()

  const [isSavingProfile, setIsSavingProfile] = useState(false)
  const [isDeletingAccount, setIsDeletingAccount] = useState(false)
  const [isEditProfileDialogVisible, setIsEditProfileDialogVisible] =
    useState(false)
  const [isDeleteAccountDialogVisible, setIsDeleteAccountDialogVisible] =
    useState(false)
  const [editDialogData, setEditDialogData] =
    useState<ProfileEditDataType>(editProfileData)

  useEffect(() => {
    if (isEditProfileDialogVisible) {
      setEditDialogData(editProfileData)
    }
  }, [editProfileData, isEditProfileDialogVisible])

  async function confirmEditProfile(data?: unknown): Promise<void> {
    const source =
      typeof data === 'object' && data !== null
        ? (data as Record<string, unknown>)
        : (editDialogData as Record<string, unknown>)

    const nextData: ProfileEditDataType = {
      firstName: String(source.firstName ?? ''),
      lastName: String(source.lastName ?? ''),
      email: String(source.email ?? ''),
      phone_number: String(source.phone_number ?? ''),
    }

    if (!nextData.firstName.trim() || !nextData.email.trim()) {
      flashToast(t('toast-name-email-required'), 'error')
      return
    }

    setIsSavingProfile(true)
    onProfileSaved?.(nextData)
    setIsSavingProfile(false)
    setIsEditProfileDialogVisible(false)
  }

  async function confirmDeleteAccount(): Promise<void> {
    setIsDeletingAccount(true)
    console.info(
      `[nuc_users] delete account requested for user ${userId} lang ${currentLang}`
    )
    setIsDeletingAccount(false)
    setIsDeleteAccountDialogVisible(false)
  }

  return (
    <div className="profile-actions-wrap">
      <p className="profile-actions-meta">
        {t('profile-account-since')} <strong>{accountSinceLabel}</strong>
      </p>

      <div className="profile-actions">
        <AdButton
          label={t('profile-edit-account')}
          nuiType="main"
          outlined
          size="small"
          disabled={isSavingProfile}
          onClick={() => setIsEditProfileDialogVisible(true)}
        />
        <AdButton
          label={t('profile-delete-account')}
          outlined
          size="small"
          severity="danger"
          disabled={isDeletingAccount}
          onClick={() => setIsDeleteAccountDialogVisible(true)}
        />
      </div>

      <AdDialog
        visible={isEditProfileDialogVisible}
        onHide={() => setIsEditProfileDialogVisible(false)}
        modal
        dismissableMask
        draggable={false}
        showHeader
        header={t('profile-edit-profile')}
        footer={
          <div className="dialog-buttons-container">
            <AdButton
              label={t('common-cancel')}
              severity="secondary"
              onClick={() => setIsEditProfileDialogVisible(false)}
            />
            <AdButton
              label={t('common-save')}
              nuiType="main"
              disabled={isSavingProfile}
              onClick={() => void confirmEditProfile(editDialogData)}
            />
          </div>
        }
      >
        <div className="form-container">
          {profileEditFields.map((field) => (
            <div key={field.name} className="form-div">
              <label htmlFor={field.name}>{t(field.label)}</label>
              <input
                id={field.name}
                value={String(
                  editDialogData[field.key as keyof ProfileEditDataType] ?? ''
                )}
                onChange={(event) =>
                  setEditDialogData((prev) => ({
                    ...prev,
                    [field.key]: event.target.value,
                  }))
                }
              />
            </div>
          ))}
        </div>
      </AdDialog>

      <AdDialog
        visible={isDeleteAccountDialogVisible}
        onHide={() => setIsDeleteAccountDialogVisible(false)}
        modal
        dismissableMask
        draggable={false}
        showHeader
        header={t('profile-delete-account')}
        footer={
          <div className="dialog-buttons-container">
            <AdButton
              label={t('common-cancel')}
              severity="secondary"
              onClick={() => setIsDeleteAccountDialogVisible(false)}
            />
            <AdButton
              label={t('common-delete')}
              severity="danger"
              disabled={isDeletingAccount}
              onClick={() => void confirmDeleteAccount()}
            />
          </div>
        }
      >
        <p>{t('profile-delete-confirm')}</p>
      </AdDialog>
    </div>
  )
}

// settings/profile/profile-actions/index.vue
<template>
  <div class="profile-actions-wrap">
    <p class="profile-actions-meta">
      {{ t('profile-account-since') }}
      <strong>{{ props.accountSinceLabel }}</strong>
    </p>

    <div class="profile-actions">
      <ad-button
        :label="t('profile-edit-account')"
        ad-type="main"
        outlined
        size="small"
        :disabled="isSavingProfile"
        @click="isEditProfileDialogVisible = true"
      />
      <ad-button
        :label="t('profile-delete-account')"
        outlined
        size="small"
        severity="danger"
        :disabled="isDeletingAccount"
        @click="isDeleteAccountDialogVisible = true"
      />
    </div>
  </div>

  <nuc-dialog
    :visible="isEditProfileDialogVisible"
    :modal="true"
    :draggable="false"
    entity="user"
    action="edit"
    :title="t('profile-edit-profile')"
    :data="editDialogData"
    :selected-object="editDialogData"
    :fields="props.profileEditFields"
    :cancel-button-label="t('common-cancel')"
    :confirm-button-label="t('common-save')"
    :confirm-button-disabled="isSavingProfile"
    :confirm="confirmEditProfile"
    :close="closeEditDialog"
    @update:visible="isEditProfileDialogVisible = $event"
  />

  <nuc-dialog
    :visible="isDeleteAccountDialogVisible"
    :modal="true"
    :draggable="false"
    action="delete"
    :title="t('profile-delete-account')"
    :selected-object="{ id: props.userId }"
    :cancel-button-label="t('common-cancel')"
    :confirm-button-label="t('common-delete')"
    :confirm-button-disabled="isDeletingAccount"
    :confirm="confirmDeleteAccount"
    :close="closeDeleteDialog"
    @update:visible="isDeleteAccountDialogVisible = $event"
  >
    <template #content> <p>{{ t('profile-delete-confirm') }}</p> </template>
  </nuc-dialog>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'

import { flashToast, userRequests } from 'nucleify'

const { t } = useI18n()

type ProfileEditDataType = {
  firstName: string
  lastName: string
  email: string
  phone_number: string
}

type ProfileEditFieldType = {
  name: string
  key: string
  label: string
  type: string
}

const props = defineProps<{
  userId: number | string
  currentLang: string
  accountSinceLabel: string
  editProfileData: ProfileEditDataType
  profileEditFields: ProfileEditFieldType[]
}>()

const { handleDeleteAccount, handleSaveProfile } = userRequests()

const isSavingProfile = ref(false)
const isDeletingAccount = ref(false)
const isEditProfileDialogVisible = ref(false)
const isDeleteAccountDialogVisible = ref(false)
const editDialogData = ref<ProfileEditDataType>({
  firstName: '',
  lastName: '',
  email: '',
  phone_number: '',
})

const emit = defineEmits<{
  profileSaved: [value: ProfileEditDataType]
}>()

const closeEditDialog = (): void => {
  isEditProfileDialogVisible.value = false
}

const closeDeleteDialog = (): void => {
  isDeleteAccountDialogVisible.value = false
}

watch(
  () => isEditProfileDialogVisible.value,
  (visible) => {
    if (visible) {
      editDialogData.value = { ...props.editProfileData }
    }
  }
)

async function confirmEditProfile(data?: ProfileEditDataType): Promise<void> {
  const firstName = data?.firstName ?? ''
  const lastName = data?.lastName ?? ''
  const email = data?.email ?? ''
  const phoneNumber = data?.phone_number ?? ''

  if (!firstName.trim() || !email.trim()) {
    flashToast(t('toast-name-email-required'), 'error')
    return
  }

  await handleSaveProfile(
    props.userId,
    firstName,
    lastName,
    email,
    phoneNumber,
    isSavingProfile
  )
  emit('profileSaved', {
    firstName,
    lastName,
    email,
    phone_number: phoneNumber,
  })
  isEditProfileDialogVisible.value = false
}

async function confirmDeleteAccount(): Promise<void> {
  await handleDeleteAccount(
    props.userId,
    props.currentLang,
    isDeleteAccountDialogVisible,
    isDeletingAccount
  )
}
</script>

<style lang="scss">
@import 'index';
</style>
